databases:
  - name: goldcinema_db
    databaseName: goldcinema
    user: goldcinema_user

services:
  - type: web
    name: goldcinema-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn goldcinema_backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.3
    build:
      rootDir: .
